# ========================================
# DOCKER COMPOSE PRODUCTION - ULUL ALBAAB
# ========================================
version: '3.8'

services:
  postgres-ulul:
    image: postgres:15-alpine
    container_name: pp-ululalbaab-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin_ulul}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-db_ululalbaab_prod}
    ports:
      - "5436:5432" # Pindah port lagi demi keamanan & isolasi
    volumes:
      - postgres_ululalbaab_prod_data:/var/lib/postgresql/data

  app-ulul:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://${POSTGRES_USER:-admin_ulul}:${POSTGRES_PASSWORD:-password123}@postgres-ulul:5432/${POSTGRES_DB:-db_ululalbaab_prod}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://ppdb.alandalus-ululalbaab.com}
        NEXTAUTH_URL: ${NEXTAUTH_URL:-https://ppdb.alandalus-ululalbaab.com}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecretkeyulul123}
    container_name: pp-ululalbaab-app
    restart: always
    ports:
      - "3001:3000" # Port diubah supaya tidak bentrok dengan Al-Imam
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin_ulul}:${POSTGRES_PASSWORD:-password123}@postgres-ulul:5432/${POSTGRES_DB:-db_ululalbaab_prod}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://ppdb.alandalus-ululalbaab.com}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecretkeyulul123}
      FAGI_WA_KEY: ${FAGI_WA_KEY}
    depends_on:
      - postgres-ulul
    volumes:
      - storage_ululalbaab_data:/app/public/storage
      - storage_ululalbaab_data:/app/storage_data

volumes:
  postgres_ululalbaab_prod_data:
  storage_ululalbaab_data:
